### ISSUE TITLE
Server Crash At Start

### ISSUE THREAD

**Issue by markgyoni** [Paneedah/Modern-Warfare-Cubed#5] opened 2023-02-27 13:53 UTC
## Describe the bug

Hey, I'm reposting the server crash bug from the old repo.

## Reproducibility

Tested with clean forge and magma --> same class error

- [x] I reproduced this issue with as few other mods as possible installed.
- [ ] I am unable to reproduce this issue consistently.

## To Reproduce

***Steps to reproduce the behavior:***

1. Install any Minecraft server
2. Install any new MW verison
3. Start

## Expected behavior

Server starts

## Logs or/and crash reports

https://mclo.gs/xTM5ppC

## Versions

- Modern Warfare Cubed: MWC-0.1-Dev-2
- Forge: 1.12.2 - 14.23.5.2860
- Java: 8

**Comment by Paneedah** [comment] 2023-02-27 17:58
This is not a bug report for `Modern Warfare Cubed`, it's a report for `Paneedah's Modern Warfare` which is no longer supported.

Please do not submit reports for issues relating to that GitHub repository here.

**Comment by markgyoni** [comment] 2023-02-27 18:02
Alright, so there is no way of running the `Paneedah's Modern Warfare` mod on a server until the new mod is completed?

**Comment by Paneedah** [comment] 2023-02-27 18:04
You should be able to run 0.1-Dev-1 without problems. Not too sure why Dev-2 isn't working, you can try to recompile it yourself instead as that might work.

**Comment by markgyoni** [comment] 2023-02-27 18:11
Sadly the same error with Dev-1.

**Comment by JustDesoroxxx** [comment] 2023-03-10 15:43
Also you probably knows, but it has been fixed with the latest dev version

**Comment by markgyoni** [comment] 2023-03-10 15:48
Yes, I'll update here if I have any more issues.

**Comment by JustDesoroxxx** [comment] 2023-03-10 15:49
Link to the dev version https://github.com/Paneedah/Modern-Warfare-Cubed/releases/tag/0.1-Dev-5

**Comment by JustDesoroxxx** [comment] 2023-03-10 15:49
Close this once you tested if the issues is fixed

**Comment by markgyoni** [comment] 2023-03-10 17:05
@atomicparticle is the other owner of our server. He'll follow up with the issues that he faced.

**Comment by atomicparticle** [comment] 2023-03-10 17:15
Hi @JustDesoroxxx , this is the error the crash produced.

---- Minecraft Crash Report ----
// Lolis deobfuscated this stacktrace using MCP's stable-39 mappings.
// Surprise! Haha. Well, this is awkward.

Time: 2023-03-10 17:53:22 CET
Description: Unexpected error

java.lang.NullPointerException
    at com.paneedah.weaponlib.render.bgl.PostProcessPipeline.prepareRainBuffer(PostProcessPipeline.java:691)
    at com.paneedah.weaponlib.render.bgl.PostProcessPipeline.drawRainBuffer(PostProcessPipeline.java:782)
    at com.paneedah.weaponlib.render.bgl.PostProcessPipeline.doWorldProcessing(PostProcessPipeline.java:614)
    at com.paneedah.weaponlib.compatibility.CompatibleClientEventHandler.renderWorrldLastEvent(CompatibleClientEventHandler.java:372)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_388_CompatibleClientEventHandler_renderWorrldLastEvent_RenderWorldLastEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(ForgeHooksClient.java:196)
    at sun.reflect.GeneratedMethodAccessor76.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.optifine.reflect.Reflector.callVoid(Reflector.java:660)
    at net.minecraft.client.renderer.EntityRenderer.renderWorldPass(EntityRenderer.java:1952)
    at net.minecraft.client.renderer.EntityRenderer.renderWorld(EntityRenderer.java:1614)
    at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1385)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1119)
    at net.minecraft.client.Minecraft.run(Minecraft.java:4114)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Affected level --
  Level name: MpServer
  All players: 1 total; [EntityPlayerSP['de_dan'/337, l='MpServer', x=1242.56, y=97.02, z=2034.89]]
  Chunk stats: MultiplayerChunkCache: 1681, 1681
  Level seed: 0
  Level generator: ID 06 - OTG, ver 0. Features enabled: false
  Level generator options: 
  Level spawn location: World: (592,133,1024), Chunk: (at 0,8,0 in 37,64; contains blocks 592,0,1024 to 607,255,1039), Region: (1,2; contains chunks 32,64 to 63,95, blocks 512,0,1024 to 1023,255,1535)
  Level time: 52434112 game time, 53156530 day time
  Level dimension: 0
  Level storage version: 0x00000 - Unknown?
  Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
  Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
  Forced entities: 18 total; [EntityPlayerSP['de_dan'/337, l='MpServer', x=1242.56, y=97.02, z=2034.89], EntityZombie['Zombie'/8200, l='MpServer', x=1249.50, y=48.00, z=2000.50], EntitySkeleton['Skeleton'/8332, l='MpServer', x=1262.50, y=92.00, z=2024.50], EntityZombie['Zombie'/8341, l='MpServer', x=1251.50, y=19.00, z=2017.50], EntityZombie['Zombie'/8342, l='MpServer', x=1252.50, y=19.00, z=2018.50], EntityZombie['Zombie'/8347, l='MpServer', x=1283.50, y=23.00, z=1999.50], EntitySkeleton['Skeleton'/8356, l='MpServer', x=1270.50, y=27.00, z=2013.50], EntityZombie['Zombie'/8357, l='MpServer', x=1269.50, y=27.00, z=2008.50], EntitySkeleton['Skeleton'/8116, l='MpServer', x=1198.50, y=81.00, z=2062.50], BuilderEntityExisting['entity.mts_entity.name'/441, l='MpServer', x=1242.56, y=97.02, z=2034.89], BuilderEntityRenderForwarder['entity.mts_entity_renderer.name'/58, l='MpServer', x=1243.17, y=98.80, z=2035.81], EntityZombie['Zombie'/8384, l='MpServer', x=1200.50, y=80.00, z=2055.50], EntitySpider['Spider'/8146, l='MpServer', x=1226.50, y=43.00, z=2037.50], EntitySpider['Spider'/8280, l='MpServer', x=1194.50, y=91.00, z=2021.50], EntityZombie['Zombie'/8282, l='MpServer', x=1282.50, y=38.00, z=2034.50], EntityZombie['Zombie'/8283, l='MpServer', x=1286.50, y=38.00, z=2038.50], EntityZombie['Zombie'/8294, l='MpServer', x=1258.50, y=41.00, z=2070.50], EntityZombie['Zombie'/8295, l='MpServer', x=1256.50, y=41.00, z=2072.50]]
  Retry entities: 0 total; []
  Server brand: Magma (Velocity)
  Server type: Non-integrated multiplayer server

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 1989781832 bytes (1897 MB) / 4932501504 bytes (4704 MB) up to 5368709120 bytes (5120 MB)
  JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx5G -XX: UnlockExperimentalVMOptions -XX: UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 LoliASM 5.6 Powered by Forge 14.23.5.2859 Optifine OptiFine_1.12.2_HD_U_F5 47 mods loaded, 47 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID                    | Version         | Source                                            | Signature                                |
       |:------ |:--------------------- |:--------------- |:------------------------------------------------- |:---------------------------------------- |
       | LCHIJA | minecraft             | 1.12.2          | minecraft.jar                                     | None                                     |
       | LCHIJA | mcp                   | 9.42            | minecraft.jar                                     | None                                     |
       | LCHIJA | FML                   | **.**.**.**       | forge-1.12.2-14.23.5.2859.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | forge                 | 14.23.5.2859    | forge-1.12.2-14.23.5.2859.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | otgcore               | 1.12.2-v9.4     | minecraft.jar                                     | None                                     |
       | LCHIJA | mixinbooter           | 7.0             | minecraft.jar                                     | None                                     |
       | LCHIJA | foamfixcore           | 7.7.4           | minecraft.jar                                     | None                                     |
       | LCHIJA | itemblacklist         | 1.4.3           | ItemBlacklist-1.4.3.jar                           | None                                     |
       | LCHIJA | replaymod             | 1.12.2-2.6.10   | replaymod-1.12.2-2.6.10.jar                       | None                                     |
       | LCHIJA | crafttweaker          | 4.1.20          | CraftTweaker2-1.12-4.1.20.683.jar                 | None                                     |
       | LCHIJA | jei                   | **.**.**.**      | jei_1.12.2-4.16.1.301.jar                         | None                                     |
       | LCHIJA | base                  | 3.14.0          | base-1.12.2-3.14.0 (1).jar                        | None                                     |
       | LCHIJA | loliasm               | 5.6             | censoredasm5.6.jar                                | None                                     |
       | LCHIJA | chameleon             | 1.12-4.1.3      | Chameleon-1.12-4.1.3.jar                          | None                                     |
       | LCHIJA | colorfularmor         | 1.0             | colorfularmor-1.12.2-1.2.jar                      | None                                     |
       | LCHIJA | contenttweaker        | 1.12.2-4.10.0   | ContentTweaker-1.12.2-4.10.0 (1).jar              | None                                     |
       | LCHIJA | corpse                | 1.12.2-1.0.8    | corpse-1.12.2-1.0.8.jar                           | None                                     |
       | LCHIJA | ctgui                 | 1.0.0           | CraftTweaker2-1.12-4.1.20.683.jar                 | None                                     |
       | LCHIJA | crafttweakerjei       | 2.0.3           | CraftTweaker2-1.12-4.1.20.683.jar                 | None                                     |
       | LCHIJA | engineersdecor        | 1.1.5           | engineersdecor-1.12.2-1.1.5.jar                   | ed58ed655893ced6280650866985abcae2bf7559 |
       | LCHIJA | foamfix               | @VERSION@       | foamfix-0.10.15-1.12.2.jar                        | None                                     |
       | LCHIJA | ftblib                | **.**.**.**         | FTBLib-5.4.7.2.jar                                | None                                     |
       | LCHIJA | itemfilters           | **.**.**.**         | ItemFilters-1.0.4.2.jar                           | None                                     |
       | LCHIJA | ftbquests             | 1202.9.0.15     | FTBQuests-1202.9.0.15.jar                         | None                                     |
       | LCHIJA | waila                 | 1.8.26          | Hwyla-1.8.26-B41_1.12.2.jar                       | None                                     |
       | LCHIJA | immersiveengineering  | 0.12-98         | ImmersiveEngineering-0.12-98.jar                  | None                                     |
       | LCHIJA | immersive_energy      | 0.5.5           | Immersive Energy-1.12.2-0.5.5.jar                 | None                                     |
       | LCHIJA | mts                   | 22.5.0-BETA     | Immersive Vehicles-1.12.2-22.5.0.jar              | None                                     |
       | LCHIJA | immersivepetroleum    | 1.1.10          | immersivepetroleum-1.12.2-1.1.10.jar              | None                                     |
       | LCHIJA | ias                   | 7.1.0           | InGameAccountSwitcher-Forge-1.12.2-7.1.0.jar      | None                                     |
       | LCHIJA | jordkrigad            | 12.0.1          | JordkrigAirDrops-1.12.2-12.0.1.jar                | 9f5e2a811a8332a842b34f6967b7db0ac4f24856 |
       | LCHIJA | loottweaker           | 0.3.1           | LootTweaker-0.3.1MC1.12.2.jar                     | None                                     |
       | LCHIJA | immersivetech         | 1.9.100         | MCTImmersiveTechnology-1.12.2-1.9.100.jar         | None                                     |
       | LCHIJA | minetraps             | 1.0.4           | MineTraps-1.12.2-(v.1.0.4).jar                    | None                                     |
       | LCHIJA | mtrm                  | **.**.**.**        | MineTweakerRecipeMaker-1.12.2-1.2.2.30.jar        | None                                     |
       | LCHIJA | openterraingenerator  | v9.4            | OpenTerrainGenerator-1.12.2-v9.4.jar              | None                                     |
       | LCHIJA | mw                    | @VERSION@       | paneedah-modern-warfare-0.1-Dev-5.jar             | None                                     |
       | LCHIJA | performant            | 1.12.2-1.5      | performant-1.11.jar                               | None                                     |
       | LCHIJA | questionablyimmersive | @VERSION@       | questionablyimmersive-1.12.2-0.1.0.jar            | None                                     |
       | LCHIJA | refinedstorage        | 1.6.16          | refinedstorage-1.6.16.jar                         | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
       | LCHIJA | storagedrawers        | 5.2.2           | StorageDrawers-1.12.2-5.4.2.jar                   | None                                     |
       | LCHIJA | unuparts              | 5.1.4           | UNU Parts Pack [MTS] 1.12.2-21.3.0-5.1.4.jar      | None                                     |
       | LCHIJA | unucivil              | 5.3.2           | UNU Civilian Pack [MTS] 1.12.2-21.3.0-5.3.2.jar   | None                                     |
       | LCHIJA | unumilitary           | 5.0.0           | UNU Military Pack [MTS] 1.12.2-21.3.0-5.0.0.jar   | None                                     |
       | LCHIJA | voicechat             | 1.12.2-2.3.28   | voicechat-forge-1.12.2-2.3.28.jar                 | None                                     |
       | LCHIJA | worldedit             | 6.1.10-SNAPSHOT | worldedit-forge-mc1.12.2-6.1.10-SNAPSHOT-dist.jar | None                                     |
       | LCHIJA | phosphor-lighting     | 1.12.2-0.2.7    | phosphor-forge-mc1.12.2-0.2.7-universal.jar       | None                                     |
  Loaded coremods (and transformers): IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
                                        blusunrize.immersiveengineering.common.asm.IEClassTransformer
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.15-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      OTGCorePlugin (OTG-Core.jar)
                                        com.pg85.otg.forge.asm.excluded.OTGClassTransformer
                                      LoliASM (censoredasm5.6.jar)
                                        
                                      PhosphorFMLLoadingPlugin (phosphor-forge-mc1.12.2-0.2.7-universal.jar)
                                        
                                      weaponlib (paneedah-modern-warfare-0.1-Dev-5.jar)
                                        com.paneedah.weaponlib.core.WeaponlibClassTransformer
                                      MixinBooter (!mixinbooter-7.0.jar)
  GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 512.78' Renderer: 'NVIDIA GeForce GTX 1650/PCIe/SSE2'
  Suspected Mods: Modern Warfare Cubed (mw), Forge Mod Loader (FML), Minecraft Forge (forge)
  Launched Version: 1.12.2-forge-14.23.5.2859
  LWJGL: 2.9.4
  OpenGL: NVIDIA GeForce GTX 1650/PCIe/SSE2 GL version 4.6.0 NVIDIA 512.78, NVIDIA Corporation
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: 
  Current Language: English (US)
  Profiler Position: N/A (disabled)
  CPU: 12x Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Client Crashes Since Restart: 1
  Integrated Server Crashes Since Restart: 0

**Comment by JustDesoroxxx** [comment] 2023-03-10 19:33
This seems to be #4 which only happens client side, it can be easily fixed by disabling the weather-related config options on client.
Are you sure this is happening on a dedicated server.

**Comment by JustDesoroxxx** [comment] 2023-03-11 14:24
I will close this as it has been not reported again and that I am also 100% certain I fixed it

**Closed by JustDesoroxxx** 2023-03-11 14:24 UTC
Labels: Bug, Need Info
